<html xmlns="http://www.w3.org/1999/xhtml"><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 
<script type="text/javascript" src="http://www.tools4noobs.com/js/dojo.js"></script> 
<script type="text/javascript" src="http://www.tools4noobs.com/js/diffview.js"></script> 
<script type="text/javascript" src="http://www.tools4noobs.com/js/difflib.js"></script> 
<link rel="stylesheet" type="text/css" href="http://www.tools4noobs.com/css/diff-style.css"> 
<link rel="stylesheet" type="text/css" href="http://www.tools4noobs.com/css/diffview.css"> 

<title>Online visual diff tool</title>
 
<script language="javascript"> 
var $ = dojo.byId;
dojo.require("dojo.io");
var url = window.location.toString().split("#")[0];
 
function diffUsingJS () {
	$("diffoptions").style.display = "none";

	var base = difflib.stringAsLines($("baseText").value);
	var newtxt = difflib.stringAsLines($("newText").value);
	var sm = new difflib.SequenceMatcher(base, newtxt);
	var opcodes = sm.get_opcodes();
	var diffoutputdiv = $("diffoutput");
	while (diffoutputdiv.firstChild) diffoutputdiv.removeChild(diffoutputdiv.firstChild);
	var contextSize = $("contextSize").value;
	contextSize = contextSize ? contextSize : null;
	diffoutputdiv.appendChild(diffview.buildView({ baseTextLines:base,
												   newTextLines:newtxt,
												   opcodes:opcodes,
												   baseTextName:"Base Text",
												   newTextName:"New Text",
												   contextSize:contextSize,
												   viewType: $("inline").checked ? 1 : 0 }));
	window.location = url + "#diff";
	
	$("diffoptionsmin").style.display = "block";
}

function showOptions()
{
	$("diffoptions").style.display = "block";
	
	$("diffoptionsmin").style.display = "none";
}
</script> 
</head> 
<body> 
	<h1>Online diff tool</h1> 
	<div id="diffoptions" style="display: block;">
	<strong>Context size (optional):</strong> <input type="text" id="contextSize" value=""><br> 
	<strong>Diff View Type:</strong> 
	<input type="radio" name="_viewtype" checked="checked" id="sidebyside"> <label for="sidebyside">Side by Side</label>
	&nbsp;&nbsp;
	<input type="radio" name="_viewtype" id="inline"> <label for="inline">Inline</label>
	<h2>Base Text</h2> 
	<textarea id="baseText" style="width:100%;height:300px"></textarea><br> 
	<h2>New Text</h2> 
	<textarea id="newText" style="width:100%;height:300px"></textarea><br> 
	<input type="button" value="Submit" onclick="javascript:diffUsingJS();"><br><br> 
	</div>
	<div id="diffoptionsmin" style="display: none;">
	<input type="button" value="Display options" onclick="javascript:showOptions();"><br><br> 
	</div>
	
	<a name="diff"> </a> 
	<div id="diffoutput" style="width:100%"><table class="diff"><thead><tr><th></th><th class="texttitle">Base Text</th><th></th><th class="texttitle">New Text</th></tr></thead><tbody><tr><th>1</th><td class="equal"></td><th>1</th><td class="equal"></td></tr><th class="author" colspan="4">diff view generated by <a href="http://snowtide.com/jsdifflib">jsdifflib</a></th></tbody></table></div> 
 
 
</body></html>