package org.app.entities;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private Review review;
	private Topic topic;
	private User user;
	private String content;
	private Date date;

	public Comment() {
	}

	public Comment(User user, String content, Date date) {
		this.user = user;
		this.content = content;
		this.date = date;
	}

	public Comment(Review review, Topic topic, User user, String content,
			Date date) {
		this.review = review;
		this.topic = topic;
		this.user = user;
		this.content = content;
		this.date = date;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Review getReview() {
		return this.review;
	}

	public void setReview(Review review) {
		this.review = review;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
