package org.app.entities;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserGroupId generated by hbm2java
 */
public class UserGroupId implements java.io.Serializable {

	private int idUser;
	private int idGroup;

	public UserGroupId() {
	}

	public UserGroupId(int idUser, int idGroup) {
		this.idUser = idUser;
		this.idGroup = idGroup;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public int getIdGroup() {
		return this.idGroup;
	}

	public void setIdGroup(int idGroup) {
		this.idGroup = idGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserGroupId))
			return false;
		UserGroupId castOther = (UserGroupId) other;

		return (this.getIdUser() == castOther.getIdUser())
				&& (this.getIdGroup() == castOther.getIdGroup());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdUser();
		result = 37 * result + this.getIdGroup();
		return result;
	}

}
