package org.coreplatform.entity;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Group generated by hbm2java
 */
public class Group implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<UserGroup> userGroups = new HashSet<UserGroup>(0);
	private Set<Topic> topics = new HashSet<Topic>(0);

	public Group() {
	}

	public Group(String name) {
		this.name = name;
	}

	public Group(String name, Set<UserGroup> userGroups, Set<Topic> topics) {
		this.name = name;
		this.userGroups = userGroups;
		this.topics = topics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<UserGroup> getUserGroups() {
		return this.userGroups;
	}

	public void setUserGroups(Set<UserGroup> userGroups) {
		this.userGroups = userGroups;
	}

	public Set<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

}
