package org.coreplatform.entity;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.springframework.stereotype.Repository;

/**
 * Review generated by hbm2java
 */
@Repository
public class Review implements java.io.Serializable {

	private Integer id;
	private Topic topic;
	private User user;
	private String description;
	private String code;
	private Date date;
	private Set<UserReviewVote> userReviewVotes = new HashSet<UserReviewVote>(0);
	private Set<Comment> comments = new HashSet<Comment>(0);

	public Review() {
	}

	public Review(String code, Date date) {
		this.code = code;
		this.date = date;
	}

	public Review(Topic topic, User user, String description, String code,
			Date date, Set<UserReviewVote> userReviewVotes,
			Set<Comment> comments) {
		this.topic = topic;
		this.user = user;
		this.description = description;
		this.code = code;
		this.date = date;
		this.userReviewVotes = userReviewVotes;
		this.comments = comments;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Topic getTopic() {
		return this.topic;
	}

	public void setTopic(Topic topic) {
		this.topic = topic;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set<UserReviewVote> getUserReviewVotes() {
		return this.userReviewVotes;
	}

	public void setUserReviewVotes(Set<UserReviewVote> userReviewVotes) {
		this.userReviewVotes = userReviewVotes;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

}
