package org.coreplatform.entity;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import org.springframework.stereotype.Repository;

/**
 * Tag generated by hbm2java
 */
@Repository
public class Tag implements java.io.Serializable {

	private Integer id;
	private String title;
	private Set<Topic> topics = new HashSet<Topic>(0);

	public Tag() {
	}

	public Tag(String title) {
		this.title = title;
	}

	public Tag(String title, Set<Topic> topics) {
		this.title = title;
		this.topics = topics;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Set<Topic> getTopics() {
		return this.topics;
	}

	public void setTopics(Set<Topic> topics) {
		this.topics = topics;
	}

}
