package org.coreplatform.entity;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private Integer id;
	private String testcol;

	public Test() {
	}

	public Test(String testcol) {
		this.testcol = testcol;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTestcol() {
		return this.testcol;
	}

	public void setTestcol(String testcol) {
		this.testcol = testcol;
	}

}
