package org.coreplatform.entity;

import org.springframework.stereotype.Repository;

// Generated Jun 3, 2014 5:42:39 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserReviewVoteId generated by hbm2java
 */
@Repository
public class UserReviewVoteId implements java.io.Serializable {

	private int userId;
	private int reviewId;

	public UserReviewVoteId() {
	}

	public UserReviewVoteId(int userId, int reviewId) {
		this.userId = userId;
		this.reviewId = reviewId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(int reviewId) {
		this.reviewId = reviewId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserReviewVoteId))
			return false;
		UserReviewVoteId castOther = (UserReviewVoteId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getReviewId() == castOther.getReviewId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getReviewId();
		return result;
	}

}
